server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: false
        same-site: lax

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/blue-line}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          strava:
            client-id: ${STRAVA_CLIENT_ID}
            client-secret: ${STRAVA_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            scope: read
            redirect-uri: ${REDIRECT_URI:http://localhost:8080/login/oauth2/code/strava}
            authorization-grant-type: authorization_code
            client-name: Strava
        provider:
          strava:
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token
            user-info-uri: https://www.strava.com/api/v3/athlete
            user-name-attribute: id

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      hibernate:
        SQL: info
      springframework:
        jdbc:
          core: info
        security: ${LOG_LEVEL:info}
    root: info

jwt:
  secret: yCEejd7w8gmc2LO4iv6vZYYW9yL2p1i3za9Fhm9ZdN2MmkFQ39t0RCWoOjC8TOnMNzH8fFVGKU6xffDYciRnAFTfakY8orzK6ShGlwJEnW4Ok9oHFUKx0XSTOrl14Ixa
  expiration: 86400000