-- liquibase formatted sql

-- changeset aurel:1733393981111-1
CREATE TABLE relationships (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, request_status VARCHAR(255) NOT NULL, user_asker_id BIGINT NOT NULL, user_receiver_id BIGINT NOT NULL, CONSTRAINT "relationshipsPK" PRIMARY KEY (id));

-- changeset aurel:1733393981111-2
ALTER TABLE relationships ADD CONSTRAINT UC_RELATIONSHIPSREQUEST_STATUS_COL UNIQUE (request_status);

-- changeset aurel:1733393981111-3
ALTER TABLE relationships ADD CONSTRAINT "FK9pj7ay5pbsvv8lrt1ib9jredu" FOREIGN KEY (user_receiver_id) REFERENCES users (id);

-- changeset aurel:1733393981111-4
ALTER TABLE relationships ADD CONSTRAINT "FKhjt1kc7gh5pyq5bxp1pcp70ru" FOREIGN KEY (user_asker_id) REFERENCES users (id);

