-- liquibase formatted sql

-- changeset aurel:1737544151614-2
CREATE TABLE "Challenge" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(500), "distanceGoal" FLOAT(53), "endDate" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, "startDate" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, "streakNbOfParticipations" INTEGER, "streakPeriod" VARCHAR(255), "timeGoal" BIGINT, type VARCHAR(255) NOT NULL, event_id BIGINT, CONSTRAINT "ChallengePK" PRIMARY KEY (id));

-- changeset aurel:1737544151614-3
CREATE TABLE "ChallengeCompletion" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "completionDate" TIMESTAMP(6) WITHOUT TIME ZONE, "distanceAchieved" FLOAT(53), "timeAchieved" BIGINT, challenge_id BIGINT NOT NULL, user_id BIGINT NOT NULL, CONSTRAINT "ChallengeCompletionPK" PRIMARY KEY (id));

-- changeset aurel:1737544151614-4
ALTER TABLE users ADD address VARCHAR(255) NOT NULL;

-- changeset aurel:1737544151614-5
ALTER TABLE users ADD gender VARCHAR(255);

-- changeset aurel:1737544151614-6
ALTER TABLE users ADD is_admin BOOLEAN NOT NULL;

-- changeset aurel:1737544151614-7
ALTER TABLE "ChallengeCompletion" ADD CONSTRAINT "FKa0r77pyd4v7ul6hrc6dbnpt9" FOREIGN KEY (challenge_id) REFERENCES "Challenge" (id);

-- changeset aurel:1737544151614-8
ALTER TABLE "ChallengeCompletion" ADD CONSTRAINT "FKi5kpq0po4f1dlalunrvvb1wp9" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset aurel:1737544151614-9
ALTER TABLE "Challenge" ADD CONSTRAINT "FKlr8pm32e1sa5lndxfgg7if746" FOREIGN KEY (event_id) REFERENCES events (id);

-- changeset aurel:1737544151614-10
ALTER TABLE relationships DROP CONSTRAINT uc_relationshipsrequest_status_col;

-- changeset aurel:1737544151614-11
ALTER TABLE users DROP COLUMN sex;

-- changeset aurel:1737544151614-1
ALTER TABLE events ALTER COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

