-- liquibase formatted sql

-- changeset aurel:1737365071752-1
CREATE TABLE event_participants (event_id BIGINT NOT NULL, user_id BIGINT NOT NULL, CONSTRAINT "event_participantsPK" PRIMARY KEY (event_id, user_id));

-- changeset aurel:1737365071752-2
CREATE TABLE events (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(500) NOT NULL, end_date TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, start_date TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, organizer_id BIGINT NOT NULL, CONSTRAINT "eventsPK" PRIMARY KEY (id));

-- changeset aurel:1737365071752-3
ALTER TABLE users ADD gender VARCHAR(255);

-- changeset aurel:1737365071752-4
ALTER TABLE users ADD is_admin BOOLEAN NOT NULL;

-- changeset aurel:1737365071752-5
ALTER TABLE events ADD CONSTRAINT UC_EVENTSNAME_COL UNIQUE (name);

-- changeset aurel:1737365071752-6
ALTER TABLE event_participants ADD CONSTRAINT "FK2x391urx4up03f4jp2y9mdt5x" FOREIGN KEY (event_id) REFERENCES events (id);

-- changeset aurel:1737365071752-7
ALTER TABLE events ADD CONSTRAINT "FKdocju8m76a3f8o6ljh2jrn2ra" FOREIGN KEY (organizer_id) REFERENCES users (id);

-- changeset aurel:1737365071752-8
ALTER TABLE event_participants ADD CONSTRAINT "FKre6m0d4mgt4351tytlkac9jvf" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset aurel:1737365071752-10
ALTER TABLE users DROP COLUMN sex;

