-- liquibase formatted sql

-- changeset aurel:1738433636225-1
CREATE TABLE activity_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, timestamp TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, user_id BIGINT NOT NULL, CONSTRAINT "activity_logsPK" PRIMARY KEY (id));

-- changeset aurel:1738433636225-2
ALTER TABLE activity_logs ADD CONSTRAINT "FK5bm1lt4f4eevt8lv2517soakd" FOREIGN KEY (user_id) REFERENCES users (id);

